---
application:
  name: "mochi-discordbot"
  project: "mochi-discordbot"
  organization: "QoveryCommunity"
databases:
- type: "MONGODB"
  name: "mochidb"
  version: "4.4"
routers:
- name: "main-mochi-discordbot"
  routes:
  - application_name: "mochi-discordbot"
    paths:
    - "/main.py"
