services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - lavalink

  lavalink:
    build:
      context: .
      dockerfile: lavalink/Dockerfile
    restart: unless-stopped
