version: "3.9"
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    network_mode: "host"
    depends_on:
      lavalink:
        condition: service_started

  lavalink:
    container_name: lavalink
    image: fredboat/lavalink:master
    build:
      context: .
      dockerfile: lavalink/Dockerfile
    ports:
      - "2333"
    restart: unless-stopped
