version: "3.9"

services:
  bot:
    container_name: ether
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      lavalink:
        condition: service_started
    links:
      - lavalink
    environment:
      - IN_DOCKER=True

  lavalink:
    container_name: lavalink
    image: fredboat/lavalink:dev
    volumes:
      - ./Lavalink/application.yml:/opt/Lavalink/application.yml
    entrypoint: java -Xmx2G -jar Lavalink.jar