version: "3.9"
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    network_mode: "host"
    depends_on:
      lavalink:
        condition: service_started

  lavalink:
    container_name: lavalink
    build:
      context: .
      dockerfile: lavalink/Dockerfile
    ports:
      - "2333:2333"
    restart: always
