version: "3.9"
services:
  mochi:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - lavalink

  lavalink:
    image: redboat/lavalink:master
    build:
      context: .
      dockerfile: lavalink/Dockerfile
    restart: unless-stopped
