services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      lavalink:
        condition: service_started

  lavalink:
    build:
      context: .
      dockerfile: lavalink/Dockerfile
    restart: unless-stopped
