name: Python Linter

on: [push, pull_request]

jobs:
  python-linter:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2  
    - name: Python Linter
      uses: sunnysid3up/python-linter@master
      with:
        source: "ether"
        mypy-options: "--ignore-missing-imports --ignore-valid-type --ignore-call-arg --show-error-codes"
        pylint-options: "--rcfile=setup.cfg"
        isort-options: "-w 100"
        django: false